# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from api import api_pb2 as api_dot_api__pb2
from core import Contract_pb2 as core_dot_Contract__pb2
from core import Tron_pb2 as core_dot_Tron__pb2


class WalletStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAccount = channel.unary_unary(
        '/protocol.Wallet/GetAccount',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Account.FromString,
        )
    self.GetAccountById = channel.unary_unary(
        '/protocol.Wallet/GetAccountById',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Account.FromString,
        )
    self.CreateTransaction = channel.unary_unary(
        '/protocol.Wallet/CreateTransaction',
        request_serializer=core_dot_Contract__pb2.TransferContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.CreateTransaction2 = channel.unary_unary(
        '/protocol.Wallet/CreateTransaction2',
        request_serializer=core_dot_Contract__pb2.TransferContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.BroadcastTransaction = channel.unary_unary(
        '/protocol.Wallet/BroadcastTransaction',
        request_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
        response_deserializer=api_dot_api__pb2.Return.FromString,
        )
    self.UpdateAccount = channel.unary_unary(
        '/protocol.Wallet/UpdateAccount',
        request_serializer=core_dot_Contract__pb2.AccountUpdateContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.SetAccountId = channel.unary_unary(
        '/protocol.Wallet/SetAccountId',
        request_serializer=core_dot_Contract__pb2.SetAccountIdContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.UpdateAccount2 = channel.unary_unary(
        '/protocol.Wallet/UpdateAccount2',
        request_serializer=core_dot_Contract__pb2.AccountUpdateContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.VoteWitnessAccount = channel.unary_unary(
        '/protocol.Wallet/VoteWitnessAccount',
        request_serializer=core_dot_Contract__pb2.VoteWitnessContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.UpdateSetting = channel.unary_unary(
        '/protocol.Wallet/UpdateSetting',
        request_serializer=core_dot_Contract__pb2.UpdateSettingContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.UpdateEnergyLimit = channel.unary_unary(
        '/protocol.Wallet/UpdateEnergyLimit',
        request_serializer=core_dot_Contract__pb2.UpdateEnergyLimitContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.VoteWitnessAccount2 = channel.unary_unary(
        '/protocol.Wallet/VoteWitnessAccount2',
        request_serializer=core_dot_Contract__pb2.VoteWitnessContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.CreateAssetIssue = channel.unary_unary(
        '/protocol.Wallet/CreateAssetIssue',
        request_serializer=core_dot_Contract__pb2.AssetIssueContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.CreateAssetIssue2 = channel.unary_unary(
        '/protocol.Wallet/CreateAssetIssue2',
        request_serializer=core_dot_Contract__pb2.AssetIssueContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.UpdateWitness = channel.unary_unary(
        '/protocol.Wallet/UpdateWitness',
        request_serializer=core_dot_Contract__pb2.WitnessUpdateContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.UpdateWitness2 = channel.unary_unary(
        '/protocol.Wallet/UpdateWitness2',
        request_serializer=core_dot_Contract__pb2.WitnessUpdateContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.CreateAccount = channel.unary_unary(
        '/protocol.Wallet/CreateAccount',
        request_serializer=core_dot_Contract__pb2.AccountCreateContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.CreateAccount2 = channel.unary_unary(
        '/protocol.Wallet/CreateAccount2',
        request_serializer=core_dot_Contract__pb2.AccountCreateContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.CreateWitness = channel.unary_unary(
        '/protocol.Wallet/CreateWitness',
        request_serializer=core_dot_Contract__pb2.WitnessCreateContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.CreateWitness2 = channel.unary_unary(
        '/protocol.Wallet/CreateWitness2',
        request_serializer=core_dot_Contract__pb2.WitnessCreateContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.TransferAsset = channel.unary_unary(
        '/protocol.Wallet/TransferAsset',
        request_serializer=core_dot_Contract__pb2.TransferAssetContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.TransferAsset2 = channel.unary_unary(
        '/protocol.Wallet/TransferAsset2',
        request_serializer=core_dot_Contract__pb2.TransferAssetContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ParticipateAssetIssue = channel.unary_unary(
        '/protocol.Wallet/ParticipateAssetIssue',
        request_serializer=core_dot_Contract__pb2.ParticipateAssetIssueContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.ParticipateAssetIssue2 = channel.unary_unary(
        '/protocol.Wallet/ParticipateAssetIssue2',
        request_serializer=core_dot_Contract__pb2.ParticipateAssetIssueContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.FreezeBalance = channel.unary_unary(
        '/protocol.Wallet/FreezeBalance',
        request_serializer=core_dot_Contract__pb2.FreezeBalanceContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.FreezeBalance2 = channel.unary_unary(
        '/protocol.Wallet/FreezeBalance2',
        request_serializer=core_dot_Contract__pb2.FreezeBalanceContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.UnfreezeBalance = channel.unary_unary(
        '/protocol.Wallet/UnfreezeBalance',
        request_serializer=core_dot_Contract__pb2.UnfreezeBalanceContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.UnfreezeBalance2 = channel.unary_unary(
        '/protocol.Wallet/UnfreezeBalance2',
        request_serializer=core_dot_Contract__pb2.UnfreezeBalanceContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.UnfreezeAsset = channel.unary_unary(
        '/protocol.Wallet/UnfreezeAsset',
        request_serializer=core_dot_Contract__pb2.UnfreezeAssetContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.UnfreezeAsset2 = channel.unary_unary(
        '/protocol.Wallet/UnfreezeAsset2',
        request_serializer=core_dot_Contract__pb2.UnfreezeAssetContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.WithdrawBalance = channel.unary_unary(
        '/protocol.Wallet/WithdrawBalance',
        request_serializer=core_dot_Contract__pb2.WithdrawBalanceContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.WithdrawBalance2 = channel.unary_unary(
        '/protocol.Wallet/WithdrawBalance2',
        request_serializer=core_dot_Contract__pb2.WithdrawBalanceContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.UpdateAsset = channel.unary_unary(
        '/protocol.Wallet/UpdateAsset',
        request_serializer=core_dot_Contract__pb2.UpdateAssetContract.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.UpdateAsset2 = channel.unary_unary(
        '/protocol.Wallet/UpdateAsset2',
        request_serializer=core_dot_Contract__pb2.UpdateAssetContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ProposalCreate = channel.unary_unary(
        '/protocol.Wallet/ProposalCreate',
        request_serializer=core_dot_Contract__pb2.ProposalCreateContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ProposalApprove = channel.unary_unary(
        '/protocol.Wallet/ProposalApprove',
        request_serializer=core_dot_Contract__pb2.ProposalApproveContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ProposalDelete = channel.unary_unary(
        '/protocol.Wallet/ProposalDelete',
        request_serializer=core_dot_Contract__pb2.ProposalDeleteContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.BuyStorage = channel.unary_unary(
        '/protocol.Wallet/BuyStorage',
        request_serializer=core_dot_Contract__pb2.BuyStorageContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.BuyStorageBytes = channel.unary_unary(
        '/protocol.Wallet/BuyStorageBytes',
        request_serializer=core_dot_Contract__pb2.BuyStorageBytesContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.SellStorage = channel.unary_unary(
        '/protocol.Wallet/SellStorage',
        request_serializer=core_dot_Contract__pb2.SellStorageContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ExchangeCreate = channel.unary_unary(
        '/protocol.Wallet/ExchangeCreate',
        request_serializer=core_dot_Contract__pb2.ExchangeCreateContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ExchangeInject = channel.unary_unary(
        '/protocol.Wallet/ExchangeInject',
        request_serializer=core_dot_Contract__pb2.ExchangeInjectContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ExchangeWithdraw = channel.unary_unary(
        '/protocol.Wallet/ExchangeWithdraw',
        request_serializer=core_dot_Contract__pb2.ExchangeWithdrawContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ExchangeTransaction = channel.unary_unary(
        '/protocol.Wallet/ExchangeTransaction',
        request_serializer=core_dot_Contract__pb2.ExchangeTransactionContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ListNodes = channel.unary_unary(
        '/protocol.Wallet/ListNodes',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.NodeList.FromString,
        )
    self.GetAssetIssueByAccount = channel.unary_unary(
        '/protocol.Wallet/GetAssetIssueByAccount',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=api_dot_api__pb2.AssetIssueList.FromString,
        )
    self.GetAccountNet = channel.unary_unary(
        '/protocol.Wallet/GetAccountNet',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=api_dot_api__pb2.AccountNetMessage.FromString,
        )
    self.GetAccountResource = channel.unary_unary(
        '/protocol.Wallet/GetAccountResource',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=api_dot_api__pb2.AccountResourceMessage.FromString,
        )
    self.GetAssetIssueByName = channel.unary_unary(
        '/protocol.Wallet/GetAssetIssueByName',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Contract__pb2.AssetIssueContract.FromString,
        )
    self.GetAssetIssueListByName = channel.unary_unary(
        '/protocol.Wallet/GetAssetIssueListByName',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AssetIssueList.FromString,
        )
    self.GetAssetIssueById = channel.unary_unary(
        '/protocol.Wallet/GetAssetIssueById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Contract__pb2.AssetIssueContract.FromString,
        )
    self.GetNowBlock = channel.unary_unary(
        '/protocol.Wallet/GetNowBlock',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )
    self.GetNowBlock2 = channel.unary_unary(
        '/protocol.Wallet/GetNowBlock2',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockExtention.FromString,
        )
    self.GetBlockByNum = channel.unary_unary(
        '/protocol.Wallet/GetBlockByNum',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )
    self.GetBlockByNum2 = channel.unary_unary(
        '/protocol.Wallet/GetBlockByNum2',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockExtention.FromString,
        )
    self.GetTransactionCountByBlockNum = channel.unary_unary(
        '/protocol.Wallet/GetTransactionCountByBlockNum',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.NumberMessage.FromString,
        )
    self.GetBlockById = channel.unary_unary(
        '/protocol.Wallet/GetBlockById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )
    self.GetBlockByLimitNext = channel.unary_unary(
        '/protocol.Wallet/GetBlockByLimitNext',
        request_serializer=api_dot_api__pb2.BlockLimit.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockList.FromString,
        )
    self.GetBlockByLimitNext2 = channel.unary_unary(
        '/protocol.Wallet/GetBlockByLimitNext2',
        request_serializer=api_dot_api__pb2.BlockLimit.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockListExtention.FromString,
        )
    self.GetBlockByLatestNum = channel.unary_unary(
        '/protocol.Wallet/GetBlockByLatestNum',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockList.FromString,
        )
    self.GetBlockByLatestNum2 = channel.unary_unary(
        '/protocol.Wallet/GetBlockByLatestNum2',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockListExtention.FromString,
        )
    self.GetTransactionById = channel.unary_unary(
        '/protocol.Wallet/GetTransactionById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.DeployContract = channel.unary_unary(
        '/protocol.Wallet/DeployContract',
        request_serializer=core_dot_Contract__pb2.CreateSmartContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.GetContract = channel.unary_unary(
        '/protocol.Wallet/GetContract',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.SmartContract.FromString,
        )
    self.TriggerContract = channel.unary_unary(
        '/protocol.Wallet/TriggerContract',
        request_serializer=core_dot_Contract__pb2.TriggerSmartContract.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.ListWitnesses = channel.unary_unary(
        '/protocol.Wallet/ListWitnesses',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.WitnessList.FromString,
        )
    self.GetDelegatedResource = channel.unary_unary(
        '/protocol.Wallet/GetDelegatedResource',
        request_serializer=api_dot_api__pb2.DelegatedResourceMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.DelegatedResourceList.FromString,
        )
    self.GetDelegatedResourceAccountIndex = channel.unary_unary(
        '/protocol.Wallet/GetDelegatedResourceAccountIndex',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.DelegatedResourceAccountIndex.FromString,
        )
    self.ListProposals = channel.unary_unary(
        '/protocol.Wallet/ListProposals',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.ProposalList.FromString,
        )
    self.GetPaginatedProposalList = channel.unary_unary(
        '/protocol.Wallet/GetPaginatedProposalList',
        request_serializer=api_dot_api__pb2.PaginatedMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.ProposalList.FromString,
        )
    self.GetProposalById = channel.unary_unary(
        '/protocol.Wallet/GetProposalById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Proposal.FromString,
        )
    self.ListExchanges = channel.unary_unary(
        '/protocol.Wallet/ListExchanges',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.ExchangeList.FromString,
        )
    self.GetPaginatedExchangeList = channel.unary_unary(
        '/protocol.Wallet/GetPaginatedExchangeList',
        request_serializer=api_dot_api__pb2.PaginatedMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.ExchangeList.FromString,
        )
    self.GetExchangeById = channel.unary_unary(
        '/protocol.Wallet/GetExchangeById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Exchange.FromString,
        )
    self.GetChainParameters = channel.unary_unary(
        '/protocol.Wallet/GetChainParameters',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.ChainParameters.FromString,
        )
    self.GetAssetIssueList = channel.unary_unary(
        '/protocol.Wallet/GetAssetIssueList',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AssetIssueList.FromString,
        )
    self.GetPaginatedAssetIssueList = channel.unary_unary(
        '/protocol.Wallet/GetPaginatedAssetIssueList',
        request_serializer=api_dot_api__pb2.PaginatedMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AssetIssueList.FromString,
        )
    self.TotalTransaction = channel.unary_unary(
        '/protocol.Wallet/TotalTransaction',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.NumberMessage.FromString,
        )
    self.GetNextMaintenanceTime = channel.unary_unary(
        '/protocol.Wallet/GetNextMaintenanceTime',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.NumberMessage.FromString,
        )
    self.GetTransactionSign = channel.unary_unary(
        '/protocol.Wallet/GetTransactionSign',
        request_serializer=core_dot_Tron__pb2.TransactionSign.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.GetTransactionSign2 = channel.unary_unary(
        '/protocol.Wallet/GetTransactionSign2',
        request_serializer=core_dot_Tron__pb2.TransactionSign.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionExtention.FromString,
        )
    self.CreateAddress = channel.unary_unary(
        '/protocol.Wallet/CreateAddress',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BytesMessage.FromString,
        )
    self.EasyTransfer = channel.unary_unary(
        '/protocol.Wallet/EasyTransfer',
        request_serializer=api_dot_api__pb2.EasyTransferMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.EasyTransferResponse.FromString,
        )
    self.EasyTransferByPrivate = channel.unary_unary(
        '/protocol.Wallet/EasyTransferByPrivate',
        request_serializer=api_dot_api__pb2.EasyTransferByPrivateMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.EasyTransferResponse.FromString,
        )
    self.GenerateAddress = channel.unary_unary(
        '/protocol.Wallet/GenerateAddress',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AddressPrKeyPairMessage.FromString,
        )
    self.GetTransactionInfoById = channel.unary_unary(
        '/protocol.Wallet/GetTransactionInfoById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.TransactionInfo.FromString,
        )


class WalletServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTransaction(self, request, context):
    """Please use CreateTransaction2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTransaction2(self, request, context):
    """Use this function instead of CreateTransaction.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BroadcastTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAccount(self, request, context):
    """Please use UpdateAccount2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetAccountId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAccount2(self, request, context):
    """Use this function instead of UpdateAccount.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VoteWitnessAccount(self, request, context):
    """Please use VoteWitnessAccount2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSetting(self, request, context):
    """modify the consume_user_resource_percent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateEnergyLimit(self, request, context):
    """modify the energy_limit
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VoteWitnessAccount2(self, request, context):
    """Use this function instead of VoteWitnessAccount.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAssetIssue(self, request, context):
    """Please use CreateAssetIssue2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAssetIssue2(self, request, context):
    """Use this function instead of CreateAssetIssue.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateWitness(self, request, context):
    """Please use UpdateWitness2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateWitness2(self, request, context):
    """Use this function instead of UpdateWitness.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAccount(self, request, context):
    """Please use CreateAccount2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAccount2(self, request, context):
    """Use this function instead of CreateAccount.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateWitness(self, request, context):
    """Please use CreateWitness2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateWitness2(self, request, context):
    """Use this function instead of CreateWitness.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferAsset(self, request, context):
    """Please use TransferAsset2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferAsset2(self, request, context):
    """Use this function instead of TransferAsset.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParticipateAssetIssue(self, request, context):
    """Please use ParticipateAssetIssue2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParticipateAssetIssue2(self, request, context):
    """Use this function instead of ParticipateAssetIssue.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FreezeBalance(self, request, context):
    """Please use FreezeBalance2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FreezeBalance2(self, request, context):
    """Use this function instead of FreezeBalance.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnfreezeBalance(self, request, context):
    """Please use UnfreezeBalance2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnfreezeBalance2(self, request, context):
    """Use this function instead of UnfreezeBalance.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnfreezeAsset(self, request, context):
    """Please use UnfreezeAsset2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnfreezeAsset2(self, request, context):
    """Use this function instead of UnfreezeAsset.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WithdrawBalance(self, request, context):
    """Please use WithdrawBalance2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WithdrawBalance2(self, request, context):
    """Use this function instead of WithdrawBalance.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAsset(self, request, context):
    """Please use UpdateAsset2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAsset2(self, request, context):
    """Use this function instead of UpdateAsset.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProposalCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProposalApprove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProposalDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuyStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuyStorageBytes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SellStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeInject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeWithdraw(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssetIssueByAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountNet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssetIssueByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssetIssueListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssetIssueById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNowBlock(self, request, context):
    """Please use GetNowBlock2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNowBlock2(self, request, context):
    """Use this function instead of GetNowBlock.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByNum(self, request, context):
    """Please use GetBlockByNum2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByNum2(self, request, context):
    """Use this function instead of GetBlockByNum.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionCountByBlockNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByLimitNext(self, request, context):
    """Please use GetBlockByLimitNext2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByLimitNext2(self, request, context):
    """Use this function instead of GetBlockByLimitNext.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByLatestNum(self, request, context):
    """Please use GetBlockByLatestNum2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByLatestNum2(self, request, context):
    """Use this function instead of GetBlockByLatestNum.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeployContract(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContract(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TriggerContract(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListWitnesses(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDelegatedResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDelegatedResourceAccountIndex(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListProposals(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPaginatedProposalList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProposalById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListExchanges(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPaginatedExchangeList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExchangeById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChainParameters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssetIssueList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPaginatedAssetIssueList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TotalTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNextMaintenanceTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionSign(self, request, context):
    """Warning: do not invoke this interface provided by others.
    Please use GetTransactionSign2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionSign2(self, request, context):
    """Warning: do not invoke this interface provided by others.
    Use this function instead of GetTransactionSign.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAddress(self, request, context):
    """Warning: do not invoke this interface provided by others.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EasyTransfer(self, request, context):
    """Warning: do not invoke this interface provided by others.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EasyTransferByPrivate(self, request, context):
    """Warning: do not invoke this interface provided by others.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateAddress(self, request, context):
    """Warning: do not invoke this interface provided by others.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionInfoById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=core_dot_Tron__pb2.Account.SerializeToString,
      ),
      'GetAccountById': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountById,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=core_dot_Tron__pb2.Account.SerializeToString,
      ),
      'CreateTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTransaction,
          request_deserializer=core_dot_Contract__pb2.TransferContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'CreateTransaction2': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTransaction2,
          request_deserializer=core_dot_Contract__pb2.TransferContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'BroadcastTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.BroadcastTransaction,
          request_deserializer=core_dot_Tron__pb2.Transaction.FromString,
          response_serializer=api_dot_api__pb2.Return.SerializeToString,
      ),
      'UpdateAccount': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAccount,
          request_deserializer=core_dot_Contract__pb2.AccountUpdateContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'SetAccountId': grpc.unary_unary_rpc_method_handler(
          servicer.SetAccountId,
          request_deserializer=core_dot_Contract__pb2.SetAccountIdContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'UpdateAccount2': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAccount2,
          request_deserializer=core_dot_Contract__pb2.AccountUpdateContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'VoteWitnessAccount': grpc.unary_unary_rpc_method_handler(
          servicer.VoteWitnessAccount,
          request_deserializer=core_dot_Contract__pb2.VoteWitnessContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'UpdateSetting': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSetting,
          request_deserializer=core_dot_Contract__pb2.UpdateSettingContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'UpdateEnergyLimit': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateEnergyLimit,
          request_deserializer=core_dot_Contract__pb2.UpdateEnergyLimitContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'VoteWitnessAccount2': grpc.unary_unary_rpc_method_handler(
          servicer.VoteWitnessAccount2,
          request_deserializer=core_dot_Contract__pb2.VoteWitnessContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'CreateAssetIssue': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAssetIssue,
          request_deserializer=core_dot_Contract__pb2.AssetIssueContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'CreateAssetIssue2': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAssetIssue2,
          request_deserializer=core_dot_Contract__pb2.AssetIssueContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'UpdateWitness': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateWitness,
          request_deserializer=core_dot_Contract__pb2.WitnessUpdateContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'UpdateWitness2': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateWitness2,
          request_deserializer=core_dot_Contract__pb2.WitnessUpdateContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'CreateAccount': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAccount,
          request_deserializer=core_dot_Contract__pb2.AccountCreateContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'CreateAccount2': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAccount2,
          request_deserializer=core_dot_Contract__pb2.AccountCreateContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'CreateWitness': grpc.unary_unary_rpc_method_handler(
          servicer.CreateWitness,
          request_deserializer=core_dot_Contract__pb2.WitnessCreateContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'CreateWitness2': grpc.unary_unary_rpc_method_handler(
          servicer.CreateWitness2,
          request_deserializer=core_dot_Contract__pb2.WitnessCreateContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'TransferAsset': grpc.unary_unary_rpc_method_handler(
          servicer.TransferAsset,
          request_deserializer=core_dot_Contract__pb2.TransferAssetContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'TransferAsset2': grpc.unary_unary_rpc_method_handler(
          servicer.TransferAsset2,
          request_deserializer=core_dot_Contract__pb2.TransferAssetContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ParticipateAssetIssue': grpc.unary_unary_rpc_method_handler(
          servicer.ParticipateAssetIssue,
          request_deserializer=core_dot_Contract__pb2.ParticipateAssetIssueContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'ParticipateAssetIssue2': grpc.unary_unary_rpc_method_handler(
          servicer.ParticipateAssetIssue2,
          request_deserializer=core_dot_Contract__pb2.ParticipateAssetIssueContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'FreezeBalance': grpc.unary_unary_rpc_method_handler(
          servicer.FreezeBalance,
          request_deserializer=core_dot_Contract__pb2.FreezeBalanceContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'FreezeBalance2': grpc.unary_unary_rpc_method_handler(
          servicer.FreezeBalance2,
          request_deserializer=core_dot_Contract__pb2.FreezeBalanceContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'UnfreezeBalance': grpc.unary_unary_rpc_method_handler(
          servicer.UnfreezeBalance,
          request_deserializer=core_dot_Contract__pb2.UnfreezeBalanceContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'UnfreezeBalance2': grpc.unary_unary_rpc_method_handler(
          servicer.UnfreezeBalance2,
          request_deserializer=core_dot_Contract__pb2.UnfreezeBalanceContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'UnfreezeAsset': grpc.unary_unary_rpc_method_handler(
          servicer.UnfreezeAsset,
          request_deserializer=core_dot_Contract__pb2.UnfreezeAssetContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'UnfreezeAsset2': grpc.unary_unary_rpc_method_handler(
          servicer.UnfreezeAsset2,
          request_deserializer=core_dot_Contract__pb2.UnfreezeAssetContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'WithdrawBalance': grpc.unary_unary_rpc_method_handler(
          servicer.WithdrawBalance,
          request_deserializer=core_dot_Contract__pb2.WithdrawBalanceContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'WithdrawBalance2': grpc.unary_unary_rpc_method_handler(
          servicer.WithdrawBalance2,
          request_deserializer=core_dot_Contract__pb2.WithdrawBalanceContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'UpdateAsset': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAsset,
          request_deserializer=core_dot_Contract__pb2.UpdateAssetContract.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'UpdateAsset2': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAsset2,
          request_deserializer=core_dot_Contract__pb2.UpdateAssetContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ProposalCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ProposalCreate,
          request_deserializer=core_dot_Contract__pb2.ProposalCreateContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ProposalApprove': grpc.unary_unary_rpc_method_handler(
          servicer.ProposalApprove,
          request_deserializer=core_dot_Contract__pb2.ProposalApproveContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ProposalDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ProposalDelete,
          request_deserializer=core_dot_Contract__pb2.ProposalDeleteContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'BuyStorage': grpc.unary_unary_rpc_method_handler(
          servicer.BuyStorage,
          request_deserializer=core_dot_Contract__pb2.BuyStorageContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'BuyStorageBytes': grpc.unary_unary_rpc_method_handler(
          servicer.BuyStorageBytes,
          request_deserializer=core_dot_Contract__pb2.BuyStorageBytesContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'SellStorage': grpc.unary_unary_rpc_method_handler(
          servicer.SellStorage,
          request_deserializer=core_dot_Contract__pb2.SellStorageContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ExchangeCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeCreate,
          request_deserializer=core_dot_Contract__pb2.ExchangeCreateContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ExchangeInject': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeInject,
          request_deserializer=core_dot_Contract__pb2.ExchangeInjectContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ExchangeWithdraw': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeWithdraw,
          request_deserializer=core_dot_Contract__pb2.ExchangeWithdrawContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ExchangeTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeTransaction,
          request_deserializer=core_dot_Contract__pb2.ExchangeTransactionContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ListNodes': grpc.unary_unary_rpc_method_handler(
          servicer.ListNodes,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.NodeList.SerializeToString,
      ),
      'GetAssetIssueByAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssetIssueByAccount,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=api_dot_api__pb2.AssetIssueList.SerializeToString,
      ),
      'GetAccountNet': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountNet,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=api_dot_api__pb2.AccountNetMessage.SerializeToString,
      ),
      'GetAccountResource': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountResource,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=api_dot_api__pb2.AccountResourceMessage.SerializeToString,
      ),
      'GetAssetIssueByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssetIssueByName,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Contract__pb2.AssetIssueContract.SerializeToString,
      ),
      'GetAssetIssueListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssetIssueListByName,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=api_dot_api__pb2.AssetIssueList.SerializeToString,
      ),
      'GetAssetIssueById': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssetIssueById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Contract__pb2.AssetIssueContract.SerializeToString,
      ),
      'GetNowBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetNowBlock,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
      'GetNowBlock2': grpc.unary_unary_rpc_method_handler(
          servicer.GetNowBlock2,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockExtention.SerializeToString,
      ),
      'GetBlockByNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByNum,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
      'GetBlockByNum2': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByNum2,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockExtention.SerializeToString,
      ),
      'GetTransactionCountByBlockNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionCountByBlockNum,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
      ),
      'GetBlockById': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
      'GetBlockByLimitNext': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByLimitNext,
          request_deserializer=api_dot_api__pb2.BlockLimit.FromString,
          response_serializer=api_dot_api__pb2.BlockList.SerializeToString,
      ),
      'GetBlockByLimitNext2': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByLimitNext2,
          request_deserializer=api_dot_api__pb2.BlockLimit.FromString,
          response_serializer=api_dot_api__pb2.BlockListExtention.SerializeToString,
      ),
      'GetBlockByLatestNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByLatestNum,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockList.SerializeToString,
      ),
      'GetBlockByLatestNum2': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByLatestNum2,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockListExtention.SerializeToString,
      ),
      'GetTransactionById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'DeployContract': grpc.unary_unary_rpc_method_handler(
          servicer.DeployContract,
          request_deserializer=core_dot_Contract__pb2.CreateSmartContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'GetContract': grpc.unary_unary_rpc_method_handler(
          servicer.GetContract,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.SmartContract.SerializeToString,
      ),
      'TriggerContract': grpc.unary_unary_rpc_method_handler(
          servicer.TriggerContract,
          request_deserializer=core_dot_Contract__pb2.TriggerSmartContract.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'ListWitnesses': grpc.unary_unary_rpc_method_handler(
          servicer.ListWitnesses,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.WitnessList.SerializeToString,
      ),
      'GetDelegatedResource': grpc.unary_unary_rpc_method_handler(
          servicer.GetDelegatedResource,
          request_deserializer=api_dot_api__pb2.DelegatedResourceMessage.FromString,
          response_serializer=api_dot_api__pb2.DelegatedResourceList.SerializeToString,
      ),
      'GetDelegatedResourceAccountIndex': grpc.unary_unary_rpc_method_handler(
          servicer.GetDelegatedResourceAccountIndex,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.DelegatedResourceAccountIndex.SerializeToString,
      ),
      'ListProposals': grpc.unary_unary_rpc_method_handler(
          servicer.ListProposals,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.ProposalList.SerializeToString,
      ),
      'GetPaginatedProposalList': grpc.unary_unary_rpc_method_handler(
          servicer.GetPaginatedProposalList,
          request_deserializer=api_dot_api__pb2.PaginatedMessage.FromString,
          response_serializer=api_dot_api__pb2.ProposalList.SerializeToString,
      ),
      'GetProposalById': grpc.unary_unary_rpc_method_handler(
          servicer.GetProposalById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Proposal.SerializeToString,
      ),
      'ListExchanges': grpc.unary_unary_rpc_method_handler(
          servicer.ListExchanges,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.ExchangeList.SerializeToString,
      ),
      'GetPaginatedExchangeList': grpc.unary_unary_rpc_method_handler(
          servicer.GetPaginatedExchangeList,
          request_deserializer=api_dot_api__pb2.PaginatedMessage.FromString,
          response_serializer=api_dot_api__pb2.ExchangeList.SerializeToString,
      ),
      'GetExchangeById': grpc.unary_unary_rpc_method_handler(
          servicer.GetExchangeById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Exchange.SerializeToString,
      ),
      'GetChainParameters': grpc.unary_unary_rpc_method_handler(
          servicer.GetChainParameters,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=core_dot_Tron__pb2.ChainParameters.SerializeToString,
      ),
      'GetAssetIssueList': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssetIssueList,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.AssetIssueList.SerializeToString,
      ),
      'GetPaginatedAssetIssueList': grpc.unary_unary_rpc_method_handler(
          servicer.GetPaginatedAssetIssueList,
          request_deserializer=api_dot_api__pb2.PaginatedMessage.FromString,
          response_serializer=api_dot_api__pb2.AssetIssueList.SerializeToString,
      ),
      'TotalTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.TotalTransaction,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
      ),
      'GetNextMaintenanceTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetNextMaintenanceTime,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
      ),
      'GetTransactionSign': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionSign,
          request_deserializer=core_dot_Tron__pb2.TransactionSign.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'GetTransactionSign2': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionSign2,
          request_deserializer=core_dot_Tron__pb2.TransactionSign.FromString,
          response_serializer=api_dot_api__pb2.TransactionExtention.SerializeToString,
      ),
      'CreateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAddress,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
      ),
      'EasyTransfer': grpc.unary_unary_rpc_method_handler(
          servicer.EasyTransfer,
          request_deserializer=api_dot_api__pb2.EasyTransferMessage.FromString,
          response_serializer=api_dot_api__pb2.EasyTransferResponse.SerializeToString,
      ),
      'EasyTransferByPrivate': grpc.unary_unary_rpc_method_handler(
          servicer.EasyTransferByPrivate,
          request_deserializer=api_dot_api__pb2.EasyTransferByPrivateMessage.FromString,
          response_serializer=api_dot_api__pb2.EasyTransferResponse.SerializeToString,
      ),
      'GenerateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateAddress,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.AddressPrKeyPairMessage.SerializeToString,
      ),
      'GetTransactionInfoById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionInfoById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.TransactionInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.Wallet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WalletSolidityStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAccount = channel.unary_unary(
        '/protocol.WalletSolidity/GetAccount',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Account.FromString,
        )
    self.GetAccountById = channel.unary_unary(
        '/protocol.WalletSolidity/GetAccountById',
        request_serializer=core_dot_Tron__pb2.Account.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Account.FromString,
        )
    self.ListWitnesses = channel.unary_unary(
        '/protocol.WalletSolidity/ListWitnesses',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.WitnessList.FromString,
        )
    self.GetAssetIssueList = channel.unary_unary(
        '/protocol.WalletSolidity/GetAssetIssueList',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AssetIssueList.FromString,
        )
    self.GetPaginatedAssetIssueList = channel.unary_unary(
        '/protocol.WalletSolidity/GetPaginatedAssetIssueList',
        request_serializer=api_dot_api__pb2.PaginatedMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AssetIssueList.FromString,
        )
    self.GetNowBlock = channel.unary_unary(
        '/protocol.WalletSolidity/GetNowBlock',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )
    self.GetNowBlock2 = channel.unary_unary(
        '/protocol.WalletSolidity/GetNowBlock2',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockExtention.FromString,
        )
    self.GetBlockByNum = channel.unary_unary(
        '/protocol.WalletSolidity/GetBlockByNum',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )
    self.GetBlockByNum2 = channel.unary_unary(
        '/protocol.WalletSolidity/GetBlockByNum2',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockExtention.FromString,
        )
    self.GetTransactionCountByBlockNum = channel.unary_unary(
        '/protocol.WalletSolidity/GetTransactionCountByBlockNum',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.NumberMessage.FromString,
        )
    self.GetDelegatedResource = channel.unary_unary(
        '/protocol.WalletSolidity/GetDelegatedResource',
        request_serializer=api_dot_api__pb2.DelegatedResourceMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.DelegatedResourceList.FromString,
        )
    self.GetDelegatedResourceAccountIndex = channel.unary_unary(
        '/protocol.WalletSolidity/GetDelegatedResourceAccountIndex',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.DelegatedResourceAccountIndex.FromString,
        )
    self.GetExchangeById = channel.unary_unary(
        '/protocol.WalletSolidity/GetExchangeById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Exchange.FromString,
        )
    self.ListExchanges = channel.unary_unary(
        '/protocol.WalletSolidity/ListExchanges',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.ExchangeList.FromString,
        )
    self.GetTransactionById = channel.unary_unary(
        '/protocol.WalletSolidity/GetTransactionById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Transaction.FromString,
        )
    self.GetTransactionInfoById = channel.unary_unary(
        '/protocol.WalletSolidity/GetTransactionInfoById',
        request_serializer=api_dot_api__pb2.BytesMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.TransactionInfo.FromString,
        )
    self.GenerateAddress = channel.unary_unary(
        '/protocol.WalletSolidity/GenerateAddress',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.AddressPrKeyPairMessage.FromString,
        )


class WalletSolidityServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListWitnesses(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssetIssueList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPaginatedAssetIssueList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNowBlock(self, request, context):
    """Please use GetNowBlock2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNowBlock2(self, request, context):
    """Use this function instead of GetNowBlock.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByNum(self, request, context):
    """Please use GetBlockByNum2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByNum2(self, request, context):
    """Use this function instead of GetBlockByNum.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionCountByBlockNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDelegatedResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDelegatedResourceAccountIndex(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExchangeById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListExchanges(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionInfoById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateAddress(self, request, context):
    """Warning: do not invoke this interface provided by others.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletSolidityServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=core_dot_Tron__pb2.Account.SerializeToString,
      ),
      'GetAccountById': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountById,
          request_deserializer=core_dot_Tron__pb2.Account.FromString,
          response_serializer=core_dot_Tron__pb2.Account.SerializeToString,
      ),
      'ListWitnesses': grpc.unary_unary_rpc_method_handler(
          servicer.ListWitnesses,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.WitnessList.SerializeToString,
      ),
      'GetAssetIssueList': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssetIssueList,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.AssetIssueList.SerializeToString,
      ),
      'GetPaginatedAssetIssueList': grpc.unary_unary_rpc_method_handler(
          servicer.GetPaginatedAssetIssueList,
          request_deserializer=api_dot_api__pb2.PaginatedMessage.FromString,
          response_serializer=api_dot_api__pb2.AssetIssueList.SerializeToString,
      ),
      'GetNowBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetNowBlock,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
      'GetNowBlock2': grpc.unary_unary_rpc_method_handler(
          servicer.GetNowBlock2,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockExtention.SerializeToString,
      ),
      'GetBlockByNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByNum,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
      'GetBlockByNum2': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByNum2,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockExtention.SerializeToString,
      ),
      'GetTransactionCountByBlockNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionCountByBlockNum,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
      ),
      'GetDelegatedResource': grpc.unary_unary_rpc_method_handler(
          servicer.GetDelegatedResource,
          request_deserializer=api_dot_api__pb2.DelegatedResourceMessage.FromString,
          response_serializer=api_dot_api__pb2.DelegatedResourceList.SerializeToString,
      ),
      'GetDelegatedResourceAccountIndex': grpc.unary_unary_rpc_method_handler(
          servicer.GetDelegatedResourceAccountIndex,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.DelegatedResourceAccountIndex.SerializeToString,
      ),
      'GetExchangeById': grpc.unary_unary_rpc_method_handler(
          servicer.GetExchangeById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Exchange.SerializeToString,
      ),
      'ListExchanges': grpc.unary_unary_rpc_method_handler(
          servicer.ListExchanges,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.ExchangeList.SerializeToString,
      ),
      'GetTransactionById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Transaction.SerializeToString,
      ),
      'GetTransactionInfoById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionInfoById,
          request_deserializer=api_dot_api__pb2.BytesMessage.FromString,
          response_serializer=core_dot_Tron__pb2.TransactionInfo.SerializeToString,
      ),
      'GenerateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateAddress,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.AddressPrKeyPairMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.WalletSolidity', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WalletExtensionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTransactionsFromThis = channel.unary_unary(
        '/protocol.WalletExtension/GetTransactionsFromThis',
        request_serializer=api_dot_api__pb2.AccountPaginated.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionList.FromString,
        )
    self.GetTransactionsFromThis2 = channel.unary_unary(
        '/protocol.WalletExtension/GetTransactionsFromThis2',
        request_serializer=api_dot_api__pb2.AccountPaginated.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionListExtention.FromString,
        )
    self.GetTransactionsToThis = channel.unary_unary(
        '/protocol.WalletExtension/GetTransactionsToThis',
        request_serializer=api_dot_api__pb2.AccountPaginated.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionList.FromString,
        )
    self.GetTransactionsToThis2 = channel.unary_unary(
        '/protocol.WalletExtension/GetTransactionsToThis2',
        request_serializer=api_dot_api__pb2.AccountPaginated.SerializeToString,
        response_deserializer=api_dot_api__pb2.TransactionListExtention.FromString,
        )


class WalletExtensionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTransactionsFromThis(self, request, context):
    """Please use GetTransactionsFromThis2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionsFromThis2(self, request, context):
    """Use this function instead of GetTransactionsFromThis.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionsToThis(self, request, context):
    """Please use GetTransactionsToThis2 instead of this function.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionsToThis2(self, request, context):
    """Use this function instead of GetTransactionsToThis.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletExtensionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTransactionsFromThis': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionsFromThis,
          request_deserializer=api_dot_api__pb2.AccountPaginated.FromString,
          response_serializer=api_dot_api__pb2.TransactionList.SerializeToString,
      ),
      'GetTransactionsFromThis2': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionsFromThis2,
          request_deserializer=api_dot_api__pb2.AccountPaginated.FromString,
          response_serializer=api_dot_api__pb2.TransactionListExtention.SerializeToString,
      ),
      'GetTransactionsToThis': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionsToThis,
          request_deserializer=api_dot_api__pb2.AccountPaginated.FromString,
          response_serializer=api_dot_api__pb2.TransactionList.SerializeToString,
      ),
      'GetTransactionsToThis2': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionsToThis2,
          request_deserializer=api_dot_api__pb2.AccountPaginated.FromString,
          response_serializer=api_dot_api__pb2.TransactionListExtention.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.WalletExtension', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DatabaseStub(object):
  """the api of tron's db
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getBlockReference = channel.unary_unary(
        '/protocol.Database/getBlockReference',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=api_dot_api__pb2.BlockReference.FromString,
        )
    self.GetDynamicProperties = channel.unary_unary(
        '/protocol.Database/GetDynamicProperties',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.DynamicProperties.FromString,
        )
    self.GetNowBlock = channel.unary_unary(
        '/protocol.Database/GetNowBlock',
        request_serializer=api_dot_api__pb2.EmptyMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )
    self.GetBlockByNum = channel.unary_unary(
        '/protocol.Database/GetBlockByNum',
        request_serializer=api_dot_api__pb2.NumberMessage.SerializeToString,
        response_deserializer=core_dot_Tron__pb2.Block.FromString,
        )


class DatabaseServicer(object):
  """the api of tron's db
  """

  def getBlockReference(self, request, context):
    """for tapos
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDynamicProperties(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNowBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatabaseServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getBlockReference': grpc.unary_unary_rpc_method_handler(
          servicer.getBlockReference,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=api_dot_api__pb2.BlockReference.SerializeToString,
      ),
      'GetDynamicProperties': grpc.unary_unary_rpc_method_handler(
          servicer.GetDynamicProperties,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=core_dot_Tron__pb2.DynamicProperties.SerializeToString,
      ),
      'GetNowBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetNowBlock,
          request_deserializer=api_dot_api__pb2.EmptyMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
      'GetBlockByNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByNum,
          request_deserializer=api_dot_api__pb2.NumberMessage.FromString,
          response_serializer=core_dot_Tron__pb2.Block.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.Database', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class NetworkStub(object):
  """the api of tron's network such as node list.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class NetworkServicer(object):
  """the api of tron's network such as node list.
  """


def add_NetworkServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.Network', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
